"""
generator.py — ASCEND TCAD Pipeline
Silvaco Victory Process (.in) script generator.

Design: pure function — no file I/O, no side effects, no logging.
Input:  TCADConfig (already validated)
Output: string (the complete .in script)

Generator dispatches on material.process_mode rather than checking
material names. This means adding a new process behavior only requires
updating materials.py — nothing here changes.

Current dispatch table:
  "deposit" → DEPOSIT MATERIAL=... THICK=...
  "mask"    → MASK "L#..." MATERIAL=... THICKNESS=... REVERSE

Usage:
    from generator import ScriptGenerator
    text = ScriptGenerator(config).generate()
"""

from datetime import datetime
from config import TCADConfig, ASCEND_VERSION
from materials import get_material

_LINE_WIDTH = 62


class ScriptGenerator:
    """
    Converts a validated TCADConfig into a Silvaco Victory Process script.

    Each section is a private method so individual parts can be unit-tested
    or overridden independently.
    """

    def __init__(self, config: TCADConfig):
        self.cfg = config
        self._used_resist: bool = False

    def generate(self) -> str:
        """Return the complete Victory Process script as a string."""
        self._used_resist = False
        parts = [
            self._header(),
            self._go_statement(),
            self._init_block(),
            self._process_steps(),
            self._strip_and_export(),
        ]
        lines: list[str] = []
        for section in parts:
            lines.extend(section)
        return "\n".join(lines) + "\n"

    # ── Section builders ───────────────────────────────────────────────────────

    def _header(self) -> list[str]:
        c = self.cfg
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return [
            "#" * _LINE_WIDTH,
            "# Victory Process Script — Auto-generated by ASCEND",
            f"# Version      : {ASCEND_VERSION}",
            f"# Project      : {c.project_name}",
            f"# Generated    : {now}",
            f"# GDS (server) : {c.gds_file_server}",
            f"# Cell         : {c.cell_name}",
            f"# Substrate    : {c.substrate_material} @ {c.substrate_thickness} µm",
            f"# Process steps: {len(c.layers)}",
            f"# Threads      : {c.simulation.num_threads}",
            "#" * _LINE_WIDTH,
            "",
        ]

    def _go_statement(self) -> list[str]:
        """Use SimulationSettings to build the go line — not hardcoded."""
        flags = self.cfg.simulation.build_simflags()
        return [
            f'go victoryprocess simflags="{flags}"',
            "",
        ]

    def _init_block(self) -> list[str]:
        c = self.cfg
        ext = c.extraction
        dop = c.doping
        sim = c.simulation
        substrate = get_material(c.substrate_material)
        gas_height = round(c.substrate_thickness + 5.0, 4)
        conc_str = sim.format_number(dop.concentration)

        init = (
            f"INIT DOPMESHFACTOR=10"
            f' MATERIAL="{substrate.silvaco_name}"'
            f' DOPANTS="{dop.dopant}"'
            f' DOPINGVALUES={conc_str}'
            f' DEPTH={c.substrate_thickness}'
            f' GASHEIGHT={gas_height}'
            f' LAYOUT="{c.gds_file_server}"'
            f' CELL="{c.cell_name}"'
            f' FROM={ext.x_from} TO={ext.x_to} AT={ext.y_at}'
            f' RESOLUTION={c.resolution}'
        )
        return [
            "# ── Step 1: Initialize substrate ──",
            init,
            "",
        ]

    def _process_steps(self) -> list[str]:
        """
        Generate one block per layer.
        Dispatch is driven by material.process_mode — no material name checks.
        """
        lines: list[str] = []

        if not self.cfg.layers:
            lines += ["# (no additional process steps defined)", ""]
            return lines

        for step_num, layer in enumerate(self.cfg.layers, start=2):
            mat = get_material(layer.material)
            lines.append(
                f"# ── Step {step_num}: {mat.name}  "
                f"(thickness = {layer.thickness} µm) ──"
            )

            if mat.process_mode == "mask":
                self._used_resist = True
                lines.append(
                    f'MASK "L#1"'
                    f' MATERIAL="{mat.silvaco_name}"'
                    f' THICKNESS={layer.thickness}'
                    f' REVERSE'
                )

            elif mat.process_mode == "deposit":
                lines.append(
                    f'DEPOSIT MATERIAL="{mat.silvaco_name}"'
                    f' THICK={layer.thickness}'
                )

            elif mat.process_mode == "etch":
                # Ready for future use — not yet triggered by any material in DB
                lines.append(
                    f'ETCH MATERIAL="{mat.silvaco_name}"'
                    f' THICK={layer.thickness}'
                )

            else:
                # Unhandled process_mode — emit a comment so the user knows
                lines.append(
                    f'# WARNING: process_mode "{mat.process_mode}" not yet '
                    f'implemented for {mat.name} — add manually'
                )

            lines.append("")

        return lines

    def _strip_and_export(self) -> list[str]:
        """Emit resist strip (only if resist was used), then save/export."""
        c = self.cfg
        lines: list[str] = []

        if self._used_resist:
            lines += [
                "# ── Strip photoresist ──",
                'STRIP MATERIAL="resist"',
                "",
            ]

        lines += [
            "# ── Save and export final structure ──",
            f'save name="{c.project_name}_Final"',
            f'export structure="{c.project_name}_Final.str"',
            "quit",
        ]
        return lines
