"""
gui.py — Streamlit UI for ASCEND TCAD Fabrication Automation Generator.
"""

import streamlit as st
import json
from datetime import datetime

# Set page layout
st.set_page_config(
    page_title="ASCEND TCAD Generator",
    page_icon="⚡",
    layout="wide"
)

st.title("ASCEND — TCAD Fabrication Automation")
st.subheader("Silvaco Victory Process Script Generator (v1.1.0)")

# Sidebar Settings
st.sidebar.header("Global Project Settings")
project_name = st.sidebar.text_input("Project Name", value="AppTest")
gds_file = st.sidebar.text_input("GDS Mask File", value="Test_Mask.gds")
cell_name = st.sidebar.text_input("GDS Cell Name", value="TOP")
num_threads = st.sidebar.number_input("Threads", min_value=1, max_value=64, value=24)
memory_limit = st.sidebar.number_input("Memory Limit (MB)", min_value=64, max_value=2048, value=128)

col1, col2 = st.columns(2)

with col1:
    st.header("Substrate Configuration")
    substrate_mat = st.selectbox("Substrate Material", ["GaAs", "Silicon", "InP"], index=0)
    substrate_thick = st.number_input("Substrate Depth (µm)", value=5.0, step=0.5)
    dopant = st.selectbox("Dopant Type", ["arsenic", "phosphorus", "boron"], index=0)
    doping_val = st.text_input("Doping Concentration (cm⁻³)", value="2.000e+20")

with col2:
    st.header("Extraction Domain Cut")
    x_from = st.number_input("X From (µm)", value=-3.0, step=0.5)
    x_to = st.number_input("X To (µm)", value=3.0, step=0.5)
    y_at = st.number_input("Y Cut (µm)", value=0.0, step=0.1)
    resolution = st.number_input("Resolution (µm)", value=1.0, step=0.1)

st.divider()
st.header("Process Layer Stack Setup")

# Dynamic Layer Builder
if "layer_count" not in st.session_state:
    st.session_state.layer_count = 4

btn_col1, btn_col2, _ = st.columns([1, 1, 4])
with btn_col1:
    if st.button("➕ Add Layer"):
        st.session_state.layer_count += 1
with btn_col2:
    if st.button("➖ Remove Layer") and st.session_state.layer_count > 1:
        st.session_state.layer_count -= 1

layers = []
has_resist = False

default_stack = [
    {"mat": "SiO2", "thick": 0.5, "model": "Conformal (ALD/CVD)"},
    {"mat": "Photoresist", "thick": 1.2, "model": "Conformal (ALD/CVD)"},
    {"mat": "Aluminum", "thick": 1.0, "model": "Conformal (ALD/CVD)"},
    {"mat": "Copper", "thick": 1.5, "model": "Conformal (ALD/CVD)"}
]

for i in range(st.session_state.layer_count):
    st.write(f"**Step {i+1}**")
    l_col1, l_col2, l_col3 = st.columns([2, 2, 3])
    
    def_mat = default_stack[i]["mat"] if i < len(default_stack) else "SiO2"
    def_thick = default_stack[i]["thick"] if i < len(default_stack) else 0.5
    def_model = default_stack[i]["model"] if i < len(default_stack) else "Conformal (ALD/CVD)"
    
    with l_col1:
        mat = st.selectbox(
            f"Material ##{i}", 
            ["SiO2", "Photoresist", "Aluminum", "Copper", "Si3N4", "Titanium", "Gold"], 
            index=["SiO2", "Photoresist", "Aluminum", "Copper", "Si3N4", "Titanium", "Gold"].index(def_mat) if def_mat in ["SiO2", "Photoresist", "Aluminum", "Copper", "Si3N4", "Titanium", "Gold"] else 0,
            key=f"mat_{i}"
        )
    with l_col2:
        thick = st.number_input(f"Thickness (µm) ##{i}", value=def_thick, step=0.1, key=f"thick_{i}")
    with l_col3:
        if mat == "Photoresist":
            has_resist = True
            model = "MASK"
            st.info("Photoresist Step → Auto-generates MASK & STRIP steps")
        else:
            model = st.selectbox(
                f"Deposition Model ##{i}", 
                ["Conformal (ALD/CVD)", "Directional (Evaporation)", "Isotropic"], 
                index=["Conformal (ALD/CVD)", "Directional (Evaporation)", "Isotropic"].index(def_model) if def_model in ["Conformal (ALD/CVD)", "Directional (Evaporation)", "Isotropic"] else 0,
                key=f"dep_model_{i}"
            )
            
    layers.append({"material": mat, "thickness": thick, "model": model})

st.divider()

# Code Generation Logic
if st.button("🚀 Build & Generate Simulation Package", type="primary"):
    
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    script_lines = [
        "##############################################################",
        "# Victory Process Script — Auto-generated by ASCEND",
        "# Version      : 1.1.0",
        f"# Project      : {project_name}",
        f"# Generated    : {now_str}",
        f"# GDS (server) : {gds_file}",
        f"# Cell         : {cell_name}",
        f"# Substrate    : {substrate_mat} @ {substrate_thick} µm",
        f"# Process steps: {len(layers)}",
        f"# Threads      : {num_threads}",
        "##############################################################",
        "",
        f'go victoryprocess simflags="-P {num_threads} -{memory_limit}"',
        "",
        "# ── Step 1: Initialize substrate ──",
        f'INIT DOPMESHFACTOR=10 MATERIAL="{substrate_mat}" DOPANTS="{dopant}" DOPINGVALUES={doping_val} DEPTH={substrate_thick} GASHEIGHT=10.0 LAYOUT="{gds_file}" CELL="{cell_name}" FROM={x_from} TO={x_to} AT={y_at} RESOLUTION={resolution}',
        ""
    ]
    
    step_num = 2
    for l in layers:
        script_lines.append(f"# ── Step {step_num}: {l['material']}  (thickness = {l['thickness']} µm) ──")
        if l['material'] == "Photoresist":
            script_lines.append(f'MASK "L#1" MATERIAL="resist" THICKNESS={l["thickness"]} REVERSE')
        else:
            sim_flag = "CONFORMAL"
            if "Directional" in l['model']:
                sim_flag = "DIRECTIONAL"
            elif "Isotropic" in l['model']:
                sim_flag = "ISOTROPIC"
            script_lines.append(f'DEPOSIT MATERIAL="{l["material"]}" THICK={l["thickness"]} {sim_flag}')
        script_lines.append("")
        step_num += 1
        
    if has_resist:
        script_lines.append("# ── Strip photoresist ──")
        script_lines.append('STRIP MATERIAL="resist"')
        script_lines.append("")
        
    script_lines.extend([
        "# ── Save and export final structure ──",
        f'save name="{project_name}_Final"',
        f'export structure="{project_name}_Final.str"',
        "quit"
    ])
    
    full_script = "\n".join(script_lines)
    
    st.success("Simulation files generated successfully!")
    st.subheader(f"Generated `{project_name}.in` Script")
    st.code(full_script, language="bash")
    
    st.download_button(
        label=f"📥 Download {project_name}.in",
        data=full_script,
        file_name=f"{project_name}.in",
        mime="text/plain"
    )
